_base_: ../base.yml
experiment_name: hgb_baseline
model:
  type: hgb_baseline
  params:
    max_depth: 3
    max_iter: 200
    class_weight: balanced
    min_samples_leaf: 40
tasks:
  basal_pattern:
    enabled: true
