_base_: ../base.yml
experiment_name: spatial_gnn
data:
  correlation_threshold: 0.6
  anatomic_weight: 0.7
model:
  type: spatial_gnn
  params:
    dropout: 0.5
    hidden_dim: 64
    num_gnn_layers: 3
    gnn_type: gat
    gnn_kwargs: {}
tasks:
  basal_pattern:
    enabled: true
training:
  learning_rate: 0.0012
  weight_decay: 0.01
